name: tiket_app
description: Aplikasi pemesanan tiket dengan OOP & Async
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  get: ^4.6.6
  
  # HTTP & API
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3
  connectivity_plus: ^5.0.2
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true